# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
sudo: required
r_build_args: "--compact-vignettes"
r_packages:
  - devtools
env:
  - COMPILER=gxx-7
matrix:
  fast_finish: true
  include:
    - os: linux
      r: release
      r_packages:
        - devtools
        - covr
      after_success:
        - Rscript codecov.R
    - os: linux
      r: devel
    - os: osx
      r: release
      env: COMPILER=clang
      before_install:
        - sudo tlmgr install placeins cleveref framed
  allow_failures:
    - os: linux
      r: devel
# see https://thecoatlessprofessor.com/programming/selecting-an-alternative-compiler-for-r-package-testing-on-travis-ci/
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - gfortran-7
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 50
  - |
    Rscript() {
      # https://github.com/travis-ci/travis-ci/issues/4190#issuecomment-353342526
      # https://unix.stackexchange.com/a/109790/219144
      while sleep 60; do echo "=====[ still running ]====="; tail -n 10 /tmp/rs.out; done &
      command Rscript "$@" > /tmp/rs.out 2>&1
      local status=$?
      kill %1
      tail -n 50 /tmp/rs.out
      return $status
    }
notifications:
  email:
    on_success: change
    on_failure: change
